# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('rwirelesscom2_timesTwo', PACKAGE = 'rwirelesscom2', x)
}

rcpp_hello <- function() {
    .Call('rwirelesscom2_rcpp_hello', PACKAGE = 'rwirelesscom2')
}

correlateCpp <- function(a, b) {
    .Call('rwirelesscom2_correlateCpp', PACKAGE = 'rwirelesscom2', a, b)
}

sinc <- function(x) {
    .Call('rwirelesscom2_sinc', PACKAGE = 'rwirelesscom2', x)
}

